\# $Id$
.Dd 4 September, 2012
.Dt topo 1
.Os Darwin
.Sh NAME
.Nm topo
.Nd Manage ssh tunnels
.Sh SYNOPSIS
.Nm
.Op Ar subcommand Op Ar arguments ...
.Sh DESCRIPTION
.Nm 
manages
secure shell 
.Nm ( ssh )
tunnels from the command line and from the scripts menu.
.Pp
A secure shell tunnel is an
secure shell
connection from the local host to a remote host through which TCP ports on the local host are forwarded to ports on destination hosts directly accessible from the remote host.
A common use of a tunnel is to gain convenient access to services on hosts behind a firewall via a bastion host.
.Pp
The tunnels managed by 
.Nm
are robust, in that once opened they are reopened after network interruptions or when the computer wakes from sleep. However, they are not persistent, in that they are not generally preserved from one login to the next. It is, however, possible to open specified tunnels at startup.
.Pp
.Nm
mean "mole" in Spanish. It is pronounced more or less like the first two syllables of the English word "topographic".
.Sh CONFIGURATION
.Nm
looks for tunnels, tunneled ports, and tunneled hosts in the standard
secure shell configuration file ~/.ssh/config.
.Pp
A port forwarded through a tunnel is referred to as a "tunneled port". A host reached by a tunneled port is referred to as a "tunneled host"; a host reached by a port that is not tunneled is referred to as a "direct host".
.Pp
Tunnels are defined by Host sections with (a) only one pattern and (b) one or more tunneled ports defined by LocalForward keywords. 
.Pp
For example, the following Host section defines a tunnel called alpha-tunnel through the host alpha and two tunneled ports, one from local TCP port 2222 to port 22 (the default ssh port) on destination host beta and another from local TCP port 8080 to port 80 (the default HTTP port) on destination host gamma:
.Bd -literal -offset indent
Host alpha-tunnel
  HostName alpha
  LocalForward 2222 beta:22
  LocalForward 8080 gamma:80	
.Ed
.Pp
The suffix "-tunnel" is optional, but conventional.
.Pp
Tunneled hosts are defined by Host sections with HostName and Port keywords that refer to a tunneled port. Continuing with the previous example, the following two host definitions define tunneled hosts that connect to the port 22 (the default ssh port) on beta and port 80 (the default HTTP port) on gamma:
.Bd -literal -offset indent
Host beta
  HostName localhost
  Port 2222

Host gamma-http
  HostName localhost
  Port 8080
.Ed
.Pp
.Nm
determines tunnel dependencies automatically. Continuing with the previous examples,
.Nm
determines that the tunneled hosts beta and gamma-http depend on the tunnel alpha-tunnel. 
.Pp
When asked to open a connection to a host, if the corresponding port is a tunneled port
.Nm
first makes sure the appropriate tunnel is open. It applies this process iteratively, so tunnels can be easily carried through other tunnels, which is useful, for example, if the destination host is behind two or more firewalls. 
.Pp
As a further example of dependencies, the following host definitions define a tunnel and tunneled host that allow access to a host delta that is accessible from beta.
.Bd -literal -offset indent
Host beta-tunnel
  HostName localhost
  Port 2222
  LocalForward 2223 delta:22

Host delta
  HostName localhost
  Port 2223
.Ed
.Pp
If
.Nm
is asked to open a connection to delta, it would first make sure that alpha-tunnel and beta-tunnel are open.
.Pp
Dependencies are determined from the local port number. This means that local ports must be uniquely assigned to tunneled hosts.
.Pp
Tunnels can be opened at start up by including a "#TunnelOpenAtStartUp" pseudo-keyword in their host section with a value of "yes". Since this keyword begins with #, it is treated as a comment by
.Nm ssh .
As with standard keywords, the interpretation of this pseudo-keyword is not sensitive to case. For example, the following host definition
.Bd -literal -offset indent
Host beta-tunnel
  #TunnelOpenAtStartUp yes
  HostName localhost
  Port 2222
  LocalForward 2223 delta:22
.Ed
.Pp
indicates that beta-tunnel (and any dependent tunnels) should be opened at start up.
.Sh AUTHENTICATION
.Nm
is designed to work best with password-less login. To this end, it makes sure that any
.Nm ssh
commands it executes run with the
.Nm SSH_AUTH_SOCK
environment variable set appropriately.
.Sh SUBCOMMANDS
.Bl -tag -width -indent
.It Xo Ar open
.Ar host
.Xc
If host is a tunnel, open the tunnel. 
If host is a tunneled host, open the corresponding tunnel.
If host is a direct host, do nothing.
.Pp
Continuing with the previous examples, both
.Bd -literal -offset indent
topo open alpha-tunnel
.Ed
.Pp
and
.Bd -literal -offset indent
topo open beta
.Ed
.Pp
would open alpha-tunnel (since the tunneled host beta depends on alpha-tunnel).
.Pp
Attempting to opening a tunnel that is already open is not an error but results in no action.
.It Xo Ar close
.Ar host
.Xc
If host is a tunnel, close the tunnel. 
Otherwise, do nothing.
.Pp
Continuing with the previous examples, 
.Bd -literal -offset indent
topo close alpha-tunnel
.Ed
.Pp
closes alpha-tunnel, but
.Bd -literal -offset indent
topo open beta
.Ed
.Pp
does nothing (since beta is not a tunnel but rather is a tunneled host).
.Pp
Closing a tunnel that is already closed is not an error.
Closing a tunnel does not close any tunnels on which the tunnel depends.
.It Xo Ar openall
.Xc
Open all tunnels.
.It Xo Ar closeall
.Xc
Close all tunnels.
.It Xo Ar ssh
.Ar host
.Op Ar arguments ...
.Xc
Open any tunnels on which host depends, and then open a
.Nm ssh
connection to host.
.Pp
Continuing with the previous examples,
.Bd -literal -offset indent
topo ssh delta
.Ed
.Pp
would open alpha-tunnel and beta-tunnel (which are dependencies of delta) and then open a ssh connection to delta.
.It Xo Ar http
.Ar host
.Ar path
.Xc
Equivalent to the url subcommand with the scheme part specified to be http.
.Pp
Continuing with the previous examples,
.Bd -literal -offset indent
topo http gamma-http a/b/c.html
.Ed
.Pp
would open alpha-tunnel (which is a dependency of gamma-http) and then open the following URL in the default browser:
.Bd -literal -offset indent
http://localhost:8080/a/b/c.html
.Ed
.Pp
This URL corresponds to the path a/b/c.html on the HTTP server running on port 80 of gamma.
.It Xo Ar https
.Ar host
.Ar path
.Xc
Equivalent to the url subcommand with the scheme part specified to be https.
.It Xo Ar url
.Ar scheme
.Ar host
.Ar path
.Xc
Open any tunnels on which host depends, construct a URL whose scheme and path part are given by the subcommand arguments, and whose host and port part refer to the forwarded port in the host definition for host, and then open the constructed URL in the default browser.
.Pp
Continuing with the previous examples,
.Bd -literal -offset indent
topo url http gamma-http a/b/c.html
.Ed
.Pp
would open alpha-tunnel (which is a dependency of gamma-http) and then open the following URL in the default browser:
.Bd -literal -offset indent
http://localhost:8080/a/b/c.html
.Ed
.Pp
This URL corresponds to the path a/b/c.html on the HTTP server running on port 80 of gamma.
.Pp
For HTTP and HTTPS connections, the http and https subcommands are more concise.
.It Xo Ar startup
.Xc
Open all tunnels whose definitions indicate (by use of the #TunnelOpenAtStartUp pseudo-keyword) that they should be opened by the
.Nm startup
subcommand.
.It Xo Ar list
.Xc
List all tunnels, together with any dependencies and whether they are configured, currently open, and opened by the
.Nm startup
subcommand.
.It Xo Ar installscripts
.Xc
Install scripts to interface to 
.Nm
in the scripts menu.
.El
.Sh FILES
.Bl -tag -width "/System/Library/LaunchDaemons" -compact
.It Pa ~/.ssh/config
The per-user ssh configuration file. Tunnel definitions are read by 
.Nm
from this file.
.El
.Sh SEE ALSO 
.Xr ssh 1 ,
.Xr ssh-agent 1 , 
and
.Xr ssh_config 5 .
